applications:
  - name: hello-world-app
    namespace: hello-world
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: default
    source:
      repoURL: https://github.com/bgagnon/mono-sample
      path: charts/hello-world
      targetRevision: HEAD
    destination:
      server: "https://hello-world.dev.gagnonagon.com"
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
  # - name: core-apps
  #   namespace: argocd
  #   finalizers:
  #     - resources-finalizer.argocd.argoproj.io
  #   project: default
  #   source:
  #     repoURL: https://github.com/bgagnon/mono-sample
  #     targetRevision: HEAD
  #     path: argocd/core
  #   destination:
  #     server: "https://kubernetes.default.svc"
  #   syncPolicy:
  #     automated:
  #       selfHeal: true
  #       prune: true
